language: python
matrix:
    include:
        - python: 3.4
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC=scipy
            - COVERAGE="no"
        - python: 3.3
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC=scipy
            - COVERAGE="no"
        - python: 2.7
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC=scipy
            - COVERAGE="yes"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq liblapack-dev libatlas-dev libatlas-base-dev gfortran swig
    - pip install --use-wheel pytest pytest-xdist six mock
    - export PIP_CMD='pip install --use-wheel'

install:
    - $PIP_CMD $NUMPY_SPEC
    - $PIP_CMD $SCIPY_SPEC
    - if [ "${COVERAGE}" == "yes" ]; then pip install coverage coveralls; fi

script:
    - if [ "${COVERAGE}" == "yes" ]; then sed -i'' -e 's/--boxed//g' pytest.ini && coverage run --source=PyDSTool setup.py test -q; else python setup.py test; fi

after_success:
    - if [ "${COVERAGE}" == "yes" ]; then coveralls; fi

cache: apt
