language: python
matrix:
    include:
        - python: 3.4
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC="scipy>=1.0,<2.0"
            - COVERAGE="no"
        - python: 2.7
          env:
            - NUMPY_SPEC=numpy
            - SCIPY_SPEC="scipy>=1.0,<2.0"
            - COVERAGE="yes"

before_install:
    - pip install --upgrade pip setuptools
    - pip install pytest pytest-xdist six mock

install:
    - pip install $NUMPY_SPEC $SCIPY_SPEC
    - if [ "${COVERAGE}" == "yes" ]; then pip install coverage==4.0.3 python-coveralls; fi

script:
    - if [ "${COVERAGE}" == "yes" ]; then sed -i'' -e 's/--boxed//g' pytest.ini && coverage run --source=PyDSTool setup.py test -q; else python setup.py test; fi

after_success:
    - if [ "${COVERAGE}" == "yes" ]; then coveralls --config_file .coveragerc; fi

cache: apt

sudo: false

addons:
    apt:
      packages:
        - gfortran
        - swig
        - liblapack-dev
        - libatlas-dev
        - libatlas-base-dev
